GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/65a99b05b9a083577cc78935
###

GET http://localhost:3001/api/persons/10
###

GET http://localhost:3001/info
###

DELETE http://localhost:3001/api/persons/1
###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name":"Meysam Zahedi",
    "number":"917-123-4567",
    "extraField":123456
}
###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name":"Meysam Zahedi"
}