GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/unknowEndpoint
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Test blog",
    "author":"good writer",
    "url":"https://www.example.com/test_blog",
    "likes":10
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Node.js blog",
    "author":"Node.js developers",
    "url":"",
    "likes":-5
}

###
DELETE http://localhost:3001/api/blogs/65b53f35eeeee9aec4756b2a

###